name: Docker container
on:
  push:
    branches:
    - container

jobs:
  run_container:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine3.1.2
    steps:
      - name: Run Docker Container
        run: |
          node -v
          cat /etc/os-release